# Generated by Django 3.0.6 on 2020-05-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('isin', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('imageURL', models.ImageField(upload_to='book_cover')),
                ('genre', models.CharField(choices=[('Business', 'Business'), ('Personal Finance', 'Personal Finance'), ('Entrepreneurship', 'Entrepreneurship'), ('Novel', 'Novel'), ('Fiction', 'Fiction'), ('Other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.IntegerField()),
                ('chapterTitle', models.CharField(max_length=50)),
                ('chapterContent', models.TextField()),
                ('bookName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookie.Book')),
            ],
        ),
    ]
