# Generated by Django 3.0.6 on 2020-05-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isin',
            new_name='isbn',
        ),
    ]
