# Generated by Django 3.0.6 on 2020-05-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0002_auto_20200527_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
